Repository geislern/DACHOR-Website, pull requests merged in 2022-10, with the labels that each got.

#52 minor fixes
  Utils/check.sh
  Utils/setup.sh
  Utils/update.sh
Labels: hacktoberfest-accepted

#60 Introduce extended custom user model with additional fields
  dachor_website/admin.py
  dachor_website/migrations/0001_user.py
  dachor_website/models.py
Labels: hacktoberfest-accepted

#66 Improve robustness with regard to extended user model
  dachor_website/migrations/0002_birthday_optional.py
  dachor_website/models.py
Labels: bug

#67 Introduce frontend login & related views
  dachor/settings.py
  dachor_website/static/css/custom.css
  dachor_website/templates/dachor_website/base.html
  dachor_website/templates/dachor_website/login.html
  dachor_website/templates/dachor_website/navbar.html
  dachor_website/templates/registration/login.html
  dachor_website/urls.py
  dachor_website/views.py
Labels: enhancement
